### PR TITLE
feat: add two clustering datasets

### PR DESCRIPTION
**Pull request by jupyterjazz**
Adding two clustering datasets:
https://huggingface.co/datasets/facebook/flores
and 
https://www.kaggle.com/datasets/kevinmorgado/spanish-news-classification

Note:
we normalized topics in flores by 1. lowercasing them, 2. removing subcategories ('travel, expenses' -> 'travel') and 3. dropping every category with less than 15 examples

### CODE REVIEW

**Comment by guenthermi** [comment]
Looks good in general, a few additional things to do:
- In https://huggingface.co/datasets/jinaai/flores_clustering you need to specify where the dataset is from, what has been done to derive it, and the license (should be the same as the license before)
- add some evaluation results for e5 multilingual base and large as in the other PRs

**Comment by jupyterjazz** [comment]
## Flores Clustering Task

| Model                    | Evaluation Time | V-Measure              |
|--------------------------|-----------------|------------------------|
| Multilingual-e5-base     | 2.46s            | 0.39178705059409646    |
| Multilingual-e5-large    | 4.45s            | 0.38976486372692465    |


## Spanish News Clustering Task

| Model                    | Evaluation Time | V-Measure              |
|--------------------------|-----------------|------------------------|
| Multilingual-e5-base     | 9.51s            | 0.44648495872748895    |
| Multilingual-e5-large    | 26.01s            | 0.4399933663826367    |

**Comment by violenil** [comment]
> ## Flores Clustering Task
> Model	Evaluation Time	V-Measure
> Multilingual-e5-base	2.46s	0.39178705059409646
> Multilingual-e5-large	4.45s	0.38976486372692465
> ## Spanish News Clustering Task
> Model	Evaluation Time	V-Measure
> Multilingual-e5-base	9.51s	0.44648495872748895
> Multilingual-e5-large	26.01s	0.4399933663826367

Isn't it weird how the large model performs worse than the base?😆

**Review by violenil — APPROVED** [review]
LGTM!

**Review by guenthermi — APPROVED** [review]
:rocket:

**Pull request merged**
